/**
 * Generate battle_trainers_sm.json from scraped Bulbapedia data.
 *
 * Battle Tree ranges based on Bulbapedia table:
 * - Trainers 001-030: appear in battles 1-10
 * - Trainers 031-090: appear in battles 11-19, 21-29
 * - Trainers 091-110: appear in battles 21-29, 31-39, 41-49, 51+
 * - Trainers 111-130: appear in battles 31-39, 41-49, 51+
 * - Trainers 131-190: appear in battles 51+
 * - Special trainers: appear at boss battles (10, 20, 30, 40, 50) in Super Course
 */

const fs = require('fs');
const path = require('path');

const trainers = [
  // Group 1: 001-030, range 1-10
  { number: 1, class: "Youngster", name: "Florian" },
  { number: 2, class: "Youngster", name: "Robin" },
  { number: 3, class: "Youngster", name: "Max" },
  { number: 4, class: "Youngster", name: "Bert" },
  { number: 5, class: "Lass", name: "Sophia" },
  { number: 6, class: "Lass", name: "Shanta" },
  { number: 7, class: "Lass", name: "Rachel" },
  { number: 8, class: "Lass", name: "Chan" },
  { number: 9, class: "Preschooler", name: "Ferdinand" },
  { number: 10, class: "Preschooler", name: "Rico" },
  { number: 11, class: "Preschooler", name: "Rocky" },
  { number: 12, class: "Preschooler", name: "Jasper" },
  { number: 13, class: "Preschooler", name: "Kendra" },
  { number: 14, class: "Preschooler", name: "Mercy" },
  { number: 15, class: "Preschooler", name: "Helen" },
  { number: 16, class: "Preschooler", name: "Gladys" },
  { number: 17, class: "Backpacker", name: "Darla" },
  { number: 18, class: "Backpacker", name: "Tammy" },
  { number: 19, class: "Backpacker", name: "Reese" },
  { number: 20, class: "Backpacker", name: "Kayla" },
  { number: 21, class: "Hiker", name: "Cleavant" },
  { number: 22, class: "Hiker", name: "Buster" },
  { number: 23, class: "Hiker", name: "Arlo" },
  { number: 24, class: "Hiker", name: "Levine" },
  { number: 25, class: "Office Worker", name: "Percy" },
  { number: 26, class: "Office Worker", name: "Conley" },
  { number: 27, class: "Office Worker", name: "Emery" },
  { number: 28, class: "Office Worker", name: "Winnie" },
  { number: 29, class: "Office Worker", name: "Prudence" },
  { number: 30, class: "Office Worker", name: "Dominica" },

  // Group 2: 031-090, range 11-19, 21-29
  { number: 31, class: "Punk Guy", name: "Kass" },
  { number: 32, class: "Punk Guy", name: "Scoop" },
  { number: 33, class: "Punk Guy", name: "Dylan" },
  { number: 34, class: "Punk Guy", name: "Evander" },
  { number: 35, class: "Punk Girl", name: "Myrna" },
  { number: 36, class: "Punk Girl", name: "Eva" },
  { number: 37, class: "Punk Girl", name: "Agrata" },
  { number: 38, class: "Punk Girl", name: "Abby" },
  { number: 39, class: "Youth Athlete", name: "Parker" },
  { number: 40, class: "Youth Athlete", name: "Isaac" },
  { number: 41, class: "Youth Athlete", name: "Ayden" },
  { number: 42, class: "Youth Athlete", name: "Alwyn" },
  { number: 43, class: "Youth Athlete", name: "Mardea" },
  { number: 44, class: "Youth Athlete", name: "Gabriella" },
  { number: 45, class: "Rising Star", name: "Ryder" },
  { number: 46, class: "Rising Star", name: "Christopher" },
  { number: 47, class: "Rising Star", name: "Sorley" },
  { number: 48, class: "Rising Star", name: "Beatrice" },
  { number: 49, class: "Rising Star", name: "Brandi" },
  { number: 50, class: "Rising Star", name: "Marsha" },
  { number: 51, class: "Sightseer", name: "Cooper" },
  { number: 52, class: "Sightseer", name: "Darien" },
  { number: 53, class: "Sightseer", name: "Hart" },
  { number: 54, class: "Sightseer", name: "Kaula" },
  { number: 55, class: "Sightseer", name: "Charlene" },
  { number: 56, class: "Sightseer", name: "Odessa" },
  { number: 57, class: "Janitor", name: "Jairo" },
  { number: 58, class: "Janitor", name: "Xaden" },
  { number: 59, class: "Janitor", name: "Giles" },
  { number: 60, class: "Worker", name: "Skip" },
  { number: 61, class: "Worker", name: "JT" },
  { number: 62, class: "Worker", name: "Benjamin" },
  { number: 63, class: "Gentleman", name: "Henry" },
  { number: 64, class: "Gentleman", name: "Ikram" },
  { number: 65, class: "Gentleman", name: "Jerry" },
  { number: 66, class: "Madame", name: "Cheryl" },
  { number: 67, class: "Madame", name: "Christy" },
  { number: 68, class: "Madame", name: "Verna" },
  { number: 69, class: "Collector", name: "Duncan" },
  { number: 70, class: "Collector", name: "Nobunaga" },
  { number: 71, class: "Golfer", name: "Arnon" },
  { number: 72, class: "Golfer", name: "Alim" },
  { number: 73, class: "Golfer", name: "Zeno" },
  { number: 74, class: "Golfer", name: "Anisa" },
  { number: 75, class: "Golfer", name: "Calliope" },
  { number: 76, class: "Golfer", name: "Christina" },
  { number: 77, class: "Pokémon Breeder", name: "Nedry" },
  { number: 78, class: "Pokémon Breeder", name: "Sheridan" },
  { number: 79, class: "Pokémon Breeder", name: "Kiernan" },
  { number: 80, class: "Pokémon Breeder", name: "Dara" },
  { number: 81, class: "Pokémon Breeder", name: "Rada" },
  { number: 82, class: "Pokémon Breeder", name: "Gertrude" },
  { number: 83, class: "Bellhop", name: "Dyson" },
  { number: 84, class: "Bellhop", name: "Chip" },
  { number: 85, class: "Bellhop", name: "Zero" },
  { number: 86, class: "Cook", name: "Julien" },
  { number: 87, class: "Cook", name: "Sly" },
  { number: 88, class: "Cook", name: "Noah" },
  { number: 89, class: "Firefighter", name: "Brantley" },
  { number: 90, class: "Firefighter", name: "Camber" },

  // Group 3: 091-110, range 21-29, 31-39, 41-49, 51+
  { number: 91, class: "Police Officer", name: "Rendor" },
  { number: 92, class: "Police Officer", name: "Lou" },
  { number: 93, class: "Police Officer", name: "Benji" },
  { number: 94, class: "Scientist", name: "Cal" },
  { number: 95, class: "Scientist", name: "Tivon" },
  { number: 96, class: "Scientist", name: "Robyn" },
  { number: 97, class: "Black Belt", name: "Chucky" },
  { number: 98, class: "Black Belt", name: "Iniko" },
  { number: 99, class: "Black Belt", name: "Arnold" },
  { number: 100, class: "Dancer", name: "Carrie" },
  { number: 101, class: "Dancer", name: "Variel" },
  { number: 102, class: "Dancer", name: "Atalanta" },
  { number: 103, class: "Aether Foundation", name: "Harvey" },
  { number: 104, class: "Aether Foundation", name: "Luke" },
  { number: 105, class: "Ace Trainer", name: "Granville" },
  { number: 106, class: "Ace Trainer", name: "Raz" },
  { number: 107, class: "Aether Foundation", name: "Heidi" },
  { number: 108, class: "Aether Foundation", name: "Haley" },
  { number: 109, class: "Ace Trainer", name: "Lea" },
  { number: 110, class: "Ace Trainer", name: "Sylvia" },

  // Group 4: 111-130, range 31-39, 41-49, 51+
  { number: 111, class: "Scientist", name: "Stein" },
  { number: 112, class: "Scientist", name: "Cadel" },
  { number: 113, class: "Black Belt", name: "Boris" },
  { number: 114, class: "Black Belt", name: "Bryson" },
  { number: 115, class: "Dancer", name: "Jo" },
  { number: 116, class: "Dancer", name: "Tasanee" },
  { number: 117, class: "Ace Trainer", name: "Levi" },
  { number: 118, class: "Ace Trainer", name: "Hashim" },
  { number: 119, class: "Ace Trainer", name: "Munin" },
  { number: 120, class: "Ace Trainer", name: "Poppy" },
  { number: 121, class: "Ace Trainer", name: "Tamah" },
  { number: 122, class: "Ace Trainer", name: "Bette" },
  { number: 123, class: "Veteran", name: "Kikujiro" },
  { number: 124, class: "Veteran", name: "Xenophon" },
  { number: 125, class: "Veteran", name: "Placido" },
  { number: 126, class: "Veteran", name: "Ignacio" },
  { number: 127, class: "Veteran", name: "Aino" },
  { number: 128, class: "Veteran", name: "Xio" },
  { number: 129, class: "Veteran", name: "Priya" },
  { number: 130, class: "Veteran", name: "Candy" },

  // Group 5: 131-190, range 51+
  { number: 131, class: "Youngster", name: "Napoleon" },
  { number: 132, class: "Youngster", name: "Brady" },
  { number: 133, class: "Lass", name: "Samantha" },
  { number: 134, class: "Lass", name: "Inez" },
  { number: 135, class: "Preschooler", name: "Niara" },
  { number: 136, class: "Preschooler", name: "Victor" },
  { number: 137, class: "Preschooler", name: "Reina" },
  { number: 138, class: "Preschooler", name: "Naya" },
  { number: 139, class: "Backpacker", name: "Gwenny" },
  { number: 140, class: "Backpacker", name: "Fernanda" },
  { number: 141, class: "Hiker", name: "Vivek" },
  { number: 142, class: "Hiker", name: "Stellan" },
  { number: 143, class: "Office Worker", name: "Savir" },
  { number: 144, class: "Office Worker", name: "Harding" },
  { number: 145, class: "Office Worker", name: "Darrel" },
  { number: 146, class: "Office Worker", name: "Jana" },
  { number: 147, class: "Punk Guy", name: "Etta" },
  { number: 148, class: "Punk Guy", name: "Dustin" },
  { number: 149, class: "Punk Girl", name: "Zed" },
  { number: 150, class: "Punk Girl", name: "Edda" },
  { number: 151, class: "Youth Athlete", name: "Leena" },
  { number: 152, class: "Youth Athlete", name: "Buddy" },
  { number: 153, class: "Youth Athlete", name: "Hilario" },
  { number: 154, class: "Youth Athlete", name: "Thamina" },
  { number: 155, class: "Rising Star", name: "Dolly" },
  { number: 156, class: "Rising Star", name: "Erix" },
  { number: 157, class: "Rising Star", name: "Joaquin" },
  { number: 158, class: "Rising Star", name: "Marianne" },
  { number: 159, class: "Sightseer", name: "Alice" },
  { number: 160, class: "Sightseer", name: "Chen" },
  { number: 161, class: "Sightseer", name: "Christian" },
  { number: 162, class: "Sightseer", name: "Ezra" },
  { number: 163, class: "Janitor", name: "Sika" },
  { number: 164, class: "Janitor", name: "Paulo" },
  { number: 165, class: "Worker", name: "Dan" },
  { number: 166, class: "Worker", name: "Omar" },
  { number: 167, class: "Gentleman", name: "Mechabob" },
  { number: 168, class: "Gentleman", name: "Abel" },
  { number: 169, class: "Madame", name: "Donny" },
  { number: 170, class: "Madame", name: "Gracie" },
  { number: 171, class: "Bellhop", name: "Donna" },
  { number: 172, class: "Bellhop", name: "Gilroy" },
  { number: 173, class: "Golfer", name: "Patrick" },
  { number: 174, class: "Golfer", name: "Moe" },
  { number: 175, class: "Golfer", name: "Bruce" },
  { number: 176, class: "Golfer", name: "Susanna" },
  { number: 177, class: "Pokémon Breeder", name: "Lori" },
  { number: 178, class: "Pokémon Breeder", name: "Colby" },
  { number: 179, class: "Pokémon Breeder", name: "Danby" },
  { number: 180, class: "Pokémon Breeder", name: "Izel" },
  { number: 181, class: "Firefighter", name: "Presta" },
  { number: 182, class: "Firefighter", name: "Calder" },
  { number: 183, class: "Cook", name: "Larry" },
  { number: 184, class: "Cook", name: "Tony" },
  { number: 185, class: "Collector", name: "Sam" },
  { number: 186, class: "Collector", name: "Dennis" },
  { number: 187, class: "Ace Trainer", name: "Horace" },
  { number: 188, class: "Pokémon Center Lady", name: "Perri" },
  { number: 189, class: "Veteran", name: "Dooley" },
  { number: 190, class: "Veteran", name: "Demiathena" },
];

function getRanges(num) {
  if (num <= 30) return ["1-10"];
  if (num <= 90) return ["11-19", "21-29"];
  if (num <= 110) return ["21-29", "31-39", "41-49", "51+"];
  if (num <= 130) return ["31-39", "41-49", "51+"];
  return ["51+"];
}

const result = trainers.map(t => ({
  number: t.number,
  class: t.class,
  name: t.name,
  battleRanges: getRanges(t.number),
}));

// Special trainers (Super Course boss battles at 10, 20, 30, 40, 50)
// Red and Blue are the main bosses at battle 20 (Normal) and 50 (Super)
const specialTrainers = [
  { number: 191, class: "Pokémon Trainer", name: "Red", battleRanges: ["20", "50"] },
  { number: 192, class: "Pokémon Trainer", name: "Blue", battleRanges: ["20", "50"] },
  { number: 193, class: "Pokémon Trainer", name: "Anabel", battleRanges: ["10", "30", "40"] },
  { number: 194, class: "Pokémon Trainer", name: "Colress", battleRanges: ["10", "30", "40"] },
  { number: 195, class: "Pokémon Trainer", name: "Cynthia", battleRanges: ["10", "30", "40"] },
  { number: 196, class: "Pokémon Trainer", name: "Dexio", battleRanges: ["10", "30", "40"] },
  { number: 197, class: "Pokémon Trainer", name: "Grimsley", battleRanges: ["10", "30", "40"] },
  { number: 198, class: "Pokémon Trainer", name: "Guzma", battleRanges: ["10", "30", "40"] },
  { number: 199, class: "Captain", name: "Kiawe", battleRanges: ["10", "30", "40"] },
  { number: 200, class: "Captain", name: "Mallow", battleRanges: ["10", "30", "40"] },
  { number: 201, class: "Pokémon Trainer", name: "Plumeria", battleRanges: ["10", "30", "40"] },
  { number: 202, class: "Pokémon Trainer", name: "Sina", battleRanges: ["10", "30", "40"] },
  { number: 203, class: "Pokémon Trainer", name: "Wally", battleRanges: ["10", "30", "40"] },
];

result.push(...specialTrainers);

const outDir = path.join(__dirname, '../../data/battle-facilities/sunmoon');
fs.writeFileSync(path.join(outDir, 'battle_trainers_sm.json'), JSON.stringify(result, null, 2));
console.log(`Wrote battle_trainers_sm.json (${result.length} trainers)`);
